spring:
  datasource:
    url: jdbc:postgresql://orders-db:5432/orders
  profiles:
    active: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

server:
  port: 2550